### ISSUE TITLE
How to Enable XA transactions for Solace Connector?

### ISSUE THREAD

**Issue by vasanth-inthub** [solace-iot-team/solace-mule-connector#1]
Hi,
Got below error when enabled XA transaction in Try scope while consuming Guaranteed Queue. How can we achieve Rollback while consuming Guaranteed Mesages?
********************************************************************************

ERROR 2021-02-02 16:31:44,852 [[MuleRuntime].uber.05: [solace-jcsmp-api-cloud].solace-jcsmp-api-cloudFlow1.BLOCKING @2aaa5b1d] [processor: ; event: 099fdd41-6546-11eb-8e04-e86a643b7791] org.mule.runtime.core.internal.exception.OnErrorPropagateHandler: 
********************************************************************************
Message               : Can not start XA transaction
Element               : solace-jcsmp-api-cloudFlow1/processors/0 @ solace-jcsmp-api-cloud:solace-jcsmp-api-cloud.xml:40 (Try)
Element DSL           : <try doc:name="Try" doc:id="73dc00cb-473e-44b7-ae9f-1219086bdc66" transactionalAction="ALWAYS_BEGIN" transactionType="XA">
                        <solace:consume doc:name="Consume" doc:id="43cf6e8e-6cfb-432c-aea7-c856e26bdf89" config-ref="Solace_Connector_Config" address="vasanth_q1" endpoint-type="QUEUE" timeOut="2000"></solace:consume>
                        <logger level="INFO" doc:name="Logger" doc:id="82cdbf95-fc9a-435a-bfbe-5e5294d3e124" message="** Queue Consumed **"></logger>
                        </try>
Error type            : MULE:UNKNOWN
FlowStack             : at solace-jcsmp-api-cloudFlow1(solace-jcsmp-api-cloudFlow1/processors/0 @ solace-jcsmp-api-cloud:solace-jcsmp-api-cloud.xml:40 (Try))
--------------------------------------------------------------------------------
Root Exception stack trace:
java.lang.IllegalStateException: Object of type "javax.transaction.TransactionManager" with name "Transaction Manager" is not available in the registry
	at org.mule.runtime.core.privileged.transaction.XaTransaction.doBegin(XaTransaction.java:83)
	at org.mule.runtime.core.privileged.transaction.AbstractTransaction.begin(AbstractTransaction.java:94)
	at org.mule.runtime.core.privileged.transaction.xa.XaTransactionFactory.beginTransaction(XaTransactionFactory.java:40)
	at org.mule.runtime.core.internal.execution.BeginAndResolveTransactionInterceptor.execute(BeginAndResolveTransactionInterceptor.java:65)
	at org.mule.runtime.core.internal.execution.SuspendXaTransactionInterceptor.execute(SuspendXaTransactionInterceptor.java:46)
	at org.mule.runtime.core.internal.execution.ValidateTransactionalStateInterceptor.execute(ValidateTransactionalStateInterceptor.java:43)
	at org.mule.runtime.core.internal.execution.IsolateCurrentTransactionInterceptor.execute(IsolateCurrentTransactionInterceptor.java:37)
	at org.mule.runtime.core.api.execution.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:139)
	at org.mule.runtime.core.internal.processor.TryScope.lambda$null$1(TryScope.java:92)
	at reactor.core.* (1 elements filtered from stack; set debug level logging or '-Dmule.verbose.exceptions=true' for everything)(Unknown Source)
	at org.mule.runtime.core.privileged.processor.chain.* (2 elements filtered from stack; set debug level logging or '-Dmule.verbose.exceptions=true' for everything)(Unknown Source)
	at reactor.core.* (6 elements filtered from stack; set debug level logging or '-Dmule.verbose.exceptions=true' for everything)(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.mule.service.scheduler.internal.AbstractRunnableFutureDecorator.doRun(AbstractRunnableFutureDecorator.java:111)
	at org.mule.service.scheduler.internal.RunnableFutureDecorator.run(RunnableFutureDecorator.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

********************************************************************************

INFO  2021-02-02 16:31:44,906 [[MuleRuntime].uber.04: [solace-jcsmp-api-cloud].solace-jcsmp-api-cloudFlow.CPU_LITE @41396840] [processor: solace-jcsmp-api-cloudFlow/processors/2; event: 099fdd40-6546-11eb-8e04-e86a643b7791] org.mule.runtime.core.internal.processor.LoggerMessageProcessor: ** Message Published to the Queue **
ERROR 2021-02-02 16:31:45,855 [[MuleRuntime].uber.04: [solace-jcsmp-api-cloud].solace-jcsmp-api-cloudFlow1.BLOCKING @2aaa5b1d] [processor: ; event: 0a38e8f0-6546-11eb-8e04-e86a643b7791] org.mule.runtime.core.internal.exception.OnErrorPropagateHandler: 
********************************************************************************
Message               : Can not start XA transaction
Element               : solace-jcsmp-api-cloudFlow1/processors/0 @ solace-jcsmp-api-cloud:solace-jcsmp-api-cloud.xml:40 (Try)
Element DSL           : <try doc:name="Try" doc:id="73dc00cb-473e-44b7-ae9f-1219086bdc66" transactionalAction="ALWAYS_BEGIN" transactionType="XA">
                        <solace:consume doc:name="Consume" doc:id="43cf6e8e-6cfb-432c-aea7-c856e26bdf89" config-ref="Solace_Connector_Config" address="vasanth_q1" endpoint-type="QUEUE" timeOut="2000"></solace:consume>
                        <logger level="INFO" doc:name="Logger" doc:id="82cdbf95-fc9a-435a-bfbe-5e5294d3e124" message="** Queue Consumed **"></logger>
                        </try>
Error type            : MULE:UNKNOWN
FlowStack             : at solace-jcsmp-api-cloudFlow1(solace-jcsmp-api-cloudFlow1/processors/0 @ solace-jcsmp-api-cloud:solace-jcsmp-api-cloud.xml:40 (Try))
--------------------------------------------------------------------------------
Root Exception stack trace:
java.lang.IllegalStateException: Object of type "javax.transaction.TransactionManager" with name "Transaction Manager" is not available in the registry
	at org.mule.runtime.core.privileged.transaction.XaTransaction.doBegin(XaTransaction.java:83)
	at org.mule.runtime.core.privileged.transaction.AbstractTransaction.begin(AbstractTransaction.java:94)
	at org.mule.runtime.core.privileged.transaction.xa.XaTransactionFactory.beginTransaction(XaTransactionFactory.java:40)
	at org.mule.runtime.core.internal.execution.BeginAndResolveTransactionInterceptor.execute(BeginAndResolveTransactionInterceptor.java:65)
	at org.mule.runtime.core.internal.execution.SuspendXaTransactionInterceptor.execute(SuspendXaTransactionInterceptor.java:46)
	at org.mule.runtime.core.internal.execution.ValidateTransactionalStateInterceptor.execute(ValidateTransactionalStateInterceptor.java:43)
	at org.mule.runtime.core.internal.execution.IsolateCurrentTransactionInterceptor.execute(IsolateCurrentTransactionInterceptor.java:37)
	at org.mule.runtime.core.api.execution.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:139)
	at org.mule.runtime.core.internal.processor.TryScope.lambda$null$1(TryScope.java:92)
	at reactor.core.* (1 elements filtered from stack; set debug level logging or '-Dmule.verbose.exceptions=true' for everything)(Unknown Source)
	at org.mule.runtime.core.privileged.processor.chain.* (2 elements filtered from stack; set debug level logging or '-Dmule.verbose.exceptions=true' for everything)(Unknown Source)
	at reactor.core.* (6 elements filtered from stack; set debug level logging or '-Dmule.verbose.exceptions=true' for everything)(Unknown Source)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.mule.service.scheduler.internal.AbstractRunnableFutureDecorator.doRun(AbstractRunnableFutureDecorator.java:111)
	at org.mule.service.scheduler.internal.RunnableFutureDecorator.run(RunnableFutureDecorator.java:54)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

********************************************************************************

**Comment by vasanth-inthub** [comment]
I Just Enabled Bitronix Transaction Manager and It's working fine. Thanks a lot for this Connector.

**Comment by 195858** [comment]
Hi,

Thanks - glad to see you found a solution and apologies for the late reply.

The connector itself doesn't really support XA - it used client acknowledgement only. I'm not sure what the results would be if its part of a XA transaction. 
At some stage I intended to look into tx/xa support. I'll set up an issue to track this.
